logo:
  #nav_mobile: images/logo-apollo-space-left.svg
  #subbrand: images/logo-apollo-subbrands-developers-space.svg
  src: 'images/logo-300.png'
  title: KepleJs Docs
  url: https://docs.keplerjs.io/

favicon: images/favicon.ico

nav_links:
  'Website':
    url: https://keplerjs.io/
  'GitHub':
    url: https://github.com/keplerjs/kepler
  'Twitter':
    url: https://twitter.com/Kepler_js
  'Blog':
    url: https://blog.keplerjs.io/